spring.application.name=learning
# 1. Die Datenbank-URL (HIER PASSIERT DIE MAGIE)
spring.datasource.url=jdbc:h2:file:./data/meine_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=passwort

# 2. JPA / Hibernate Einstellungen
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# "update" erstellt Tabellen neu, wenn sie fehlen, löscht sie aber nicht beim Neustart
spring.jpa.hibernate.ddl-auto= update

# 3. H2 Web-Konsole aktivieren (Sehr praktisch zum Testen!)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true